spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loans:
  message: "Welcome to Loans Service"
  contactDetails:
    name: "Ashish Dongol Product Owner"
    email: "ashishDongol32@gmailcom"
  onCallSupport:
    - 20202020202
    - 34782734939